- name: Open FirewalldD ports
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  loop:
    - "3001/tcp" # uptime-kuma
  notify:
    - Reload firewalld
