- name: Open FirewalldD ports
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  loop:
    - "3000/tcp" # grafana
    - "8086/tcp" # influxdb2
    - "9090/tcp" # prometheus
    - "3001/tcp" # uptime-kuma
  notify:
    - Reload FirewallD
