- name: Create folder for Speedtest-tracker config files
  ansible.builtin.file:
    path: "{{ podman_appdata_dir }}/speedtest-tracker/config"
    state: directory
    owner: "{{ podman_user }}"
    group: "{{ podman_group }}"
    mode: "0755"
- name: Copy Speedtest-tracker environment files
  ansible.builtin.copy:
    src: "speedtest-tracker.env"
    dest: "{{ quadlet_dir }}"
    owner: "{{ podman_user }}"
    group: "{{ podman_group }}"
    mode: "0600"
- name: Create Speedtest-tracker Quadlet
  containers.podman.podman_container:
    name: speedtest-tracker
    image: lscr.io/linuxserver/speedtest-tracker:1.6.6@sha256:f63b6f58da10ce6d33312e09a1550888165d48cdb38bf916eb00b4e88ae93b58
    state: quadlet
    quadlet_filename: speedtest-tracker
    quadlet_file_mode: "0644"
    quadlet_dir: "{{ quadlet_dir }}"
    ports:
      - "8080:80"
    volumes:
      - "{{ podman_appdata_dir }}/speedtest-tracker/config:/config:Z"
    env_file:
      - speedtest-tracker.env
    quadlet_options:
      - "NoNewPrivileges=true"
      - |
        [Service]
        Restart=always
      - |
        [Install]
        WantedBy=default.target
- name: Open firewalld port for Speedtest-tracker
  ansible.posix.firewalld:
    port: "8080/tcp"
    permanent: true
    immediate: true
    state: enabled
  notify:
    - Reload firewalld
- name: Restart Speedtest-tracker service
  ansible.builtin.systemd_service:
    name: speedtest-tracker.service
    state: "restarted"
    scope: "user"
    daemon_reload: true
    enabled: true
  become: true
  become_user: "{{ podman_user }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ __user_info.uid }}"
