- name: Create uptime-kuma quadlet
  containers.podman.podman_container:
    name: uptime-kuma
    image: docker.io/louislam/uptime-kuma:1
    state: quadlet
    quadlet_filename: uptime-kuma
    quadlet_dir: "{{ quadlet_dir }}"
    ports:
      - "3001:3001"
    volumes:
      - "{{ podman_appdata_dir }}/uptime-kuma/data:/app/data:Z"
    quadlet_options:
      - "NoNewPrivileges=true"
      - |
        [Service]
        Restart=always
      - |
        [Install]
        WantedBy=default.target
