- name: Create folders for Actual Budget data files
  ansible.builtin.file:
    path: "{{ podman_appdata_dir }}/actual-budget/data"
    state: directory
    owner: "{{ podman_user }}"
    group: "{{ podman_group }}"
- name: Create Actual Buget Quadlet
  containers.podman.podman_container:
    name: actual-budget
    image: docker.io/actualbudget/actual-server:25.8.0@sha256:3d7fb08d3b405426e8625013a5ed95f5015e6c04d0f044e2e3fe7d7b7a41951b
    state: quadlet
    quadlet_filename: actual-budget
    quadlet_dir: "{{ quadlet_dir }}"
    ports:
      - "5006:5006"
    volumes:
      - "{{ podman_appdata_dir }}/actual-budget/data:/data:Z"
    quadlet_options:
      - "AutoUpdate=registry"
      - "NoNewPrivileges=true"
      - |
        [Service]
        Restart=always
      - |
        [Install]
        WantedBy=default.target
- name: Open firewalld port for Actual Budget
  ansible.posix.firewalld:
    port: "5006/tcp"
    permanent: true
    immediate: true
    state: enabled
  notify:
    - Reload firewalld
- name: Restart Actual Budget service
  ansible.builtin.systemd_service:
    name: actual-budget.service
    state: "restarted"
    scope: "user"
    daemon_reload: true
    enabled: true
  become_user: "{{ podman_user }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ __user_info.uid }}"
