---
- name: Create folder for Changedetection data
  ansible.builtin.file:
    path: "{{ podman_appdata_dir }}/changedetection/datastore"
    state: directory
    owner: "{{ podman_user }}"
    group: "{{ podman_group }}"
    mode: "0755"
- name: Copy Changedetection environment files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ quadlet_dir }}"
    owner: "{{ podman_user }}"
    group: "{{ podman_group }}"
    mode: "0600"
  loop:
    - changedetection.env
    - chromium-playwright.env
- name: Create changedetection pod
  containers.podman.podman_pod:
    name: changedetection
    state: quadlet
    quadlet_filename: changedetection
    quadlet_file_mode: "0644"
    quadlet_dir: "{{ quadlet_dir }}"
    infra_name: "changedetection-pod"
    ports:
      - "5000:5000"
- name: Create chromium-playwright Quadlet
  containers.podman.podman_container:
    name: chromium-playwright
    image: ghcr.io/browserless/chromium:v2.43.0@sha256:853e6f105b51aeed54b78f576dd88015e0d434300bcf4b0214afe70c6d31ed47
    state: quadlet
    quadlet_filename: chromium-playwright
    quadlet_file_mode: "0644"
    quadlet_dir: "{{ quadlet_dir }}"
    pod: changedetection.pod
    env_file:
      - chromium-playwright.env
    shm_size: "2gb"
    quadlet_options:
      - "NoNewPrivileges=true"
      - |
        [Service]
        Restart=always
      - |
        [Install]
        WantedBy=default.target
- name: Create changedetection Quadlet
  containers.podman.podman_container:
    name: changedetection
    image: ghcr.io/dgtlmoon/changedetection.io:0.54.5@sha256:02a72f0e851e3cba08220f982fc589dbffa189b5fa626efee196d7d011e4c8c5
    state: quadlet
    quadlet_filename: changedetection
    quadlet_file_mode: "0644"
    quadlet_dir: "{{ quadlet_dir }}"
    pod: changedetection.pod
    volumes:
      - "{{ podman_appdata_dir }}/changedetection/datastore:/datastore:Z"
    env_file:
      - changedetection.env
    quadlet_options:
      - "NoNewPrivileges=true"
      - |
        [Unit]
        Requires=chromium-playwright.service
        After=chromium-playwright.service
      - |
        [Service]
        Restart=always
      - |
        [Install]
        WantedBy=default.target
- name: Open firewalld port for Changedetection
  ansible.posix.firewalld:
    port: "5000/tcp"
    permanent: true
    immediate: true
    state: enabled
  notify:
    - Reload firewalld
