- name: Create folder for Changedetection data
  ansible.builtin.file:
    path: "{{ podman_appdata_dir }}/changedetection/datastore"
    state: directory
    owner: "{{ podman_user }}"
    group: "{{ podman_group }}"
    mode: "0755"
- name: Copy Changedetection environment files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ quadlet_dir }}"
    owner: "{{ podman_user }}"
    group: "{{ podman_group }}"
    mode: "0600"
  loop:
    - changedetection.env
    - chromium-playwright.env
- name: Create changedetection pod
  containers.podman.podman_pod:
    name: changedetection
    state: quadlet
    quadlet_filename: changedetection
    quadlet_dir: "{{ quadlet_dir }}"
    infra_name: "changedetection-pod"
    ports:
      - "5000:5000"
- name: Create chromium-playwright Quadlet
  containers.podman.podman_container:
    name: chromium-playwright
    image: ghcr.io/browserless/chromium:v2.37.1@sha256:730733ba9a90f3c8b4627405807a96949ef384a873fe67fe9b13515863e77309
    state: quadlet
    quadlet_filename: chromium-playwright
    quadlet_dir: "{{ quadlet_dir }}"
    pod: changedetection.pod
    env_file:
      - chromium-playwright.env
    shm_size: "2gb"
    quadlet_options:
      - "NoNewPrivileges=true"
      - |
        [Service]
        Restart=always
      - |
        [Install]
        WantedBy=default.target
- name: Create changedetection Quadlet
  containers.podman.podman_container:
    name: changedetection
    image: ghcr.io/dgtlmoon/changedetection.io:0.50.18@sha256:bef888d9b8012410ba97778dea85e3c4bd708c0c2810825b7084c5879800c131
    state: quadlet
    quadlet_filename: changedetection
    quadlet_dir: "{{ quadlet_dir }}"
    pod: changedetection.pod
    volumes:
      - "{{ podman_appdata_dir }}/changedetection/datastore:/datastore:Z"
    env_file:
      - changedetection.env
    quadlet_options:
      - "NoNewPrivileges=true"
      - |
        [Unit]
        Requires=chromium-playwright.service
        After=chromium-playwright.service
      - |
        [Service]
        Restart=always
      - |
        [Install]
        WantedBy=default.target
- name: Open firewalld port for Changedetection
  ansible.posix.firewalld:
    port: "5000/tcp"
    permanent: true
    immediate: true
    state: enabled
  notify:
    - Reload firewalld
- name: Restart Changedetection pod service
  ansible.builtin.systemd_service:
    name: changedetection-pod.service
    state: "restarted"
    scope: "user"
    daemon_reload: true
    enabled: true
  become_user: "{{ podman_user }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ __user_info.uid }}"
