---
- name: Create folders for Paperless-ngx config files
  ansible.builtin.file:
    path: "{{ podman_appdata_dir }}/{{ item }}"
    state: directory
    owner: "{{ podman_user }}"
    group: "{{ podman_group }}"
    mode: "0755"
  loop:
    - paperless-ngx/redis
    - paperless-ngx/postgres
    - paperless-ngx/data
    - paperless-ngx/media
    - paperless-ngx/export
    - paperless-ngx/consume
- name: Copy Paperless-ngx environment files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ quadlet_dir }}"
    owner: "{{ podman_user }}"
    group: "{{ podman_group }}"
    mode: "0600"
  loop:
    - paperless-ngx-redis.env
    - paperless-ngx-postgres.env
- name: Create Paperless-ngx database password
  containers.podman.podman_secret:
    state: present
    name: paperless_db_paperless_passwd
    data: "{{ paperless_db_paperless_passwd }}"
  become_user: "{{ podman_user }}"
- name: Create Paperless-ngx secret paperless_secret_key
  containers.podman.podman_secret:
    state: present
    name: paperless_secret_key
    data: "{{ paperless_secret_key }}"
  become_user: "{{ podman_user }}"
- name: Generate paperless-ngx.env from template
  ansible.builtin.template:
    src: "{{ paperless_ngx_env_template_file }}"
    dest: "{{ quadlet_dir }}/paperless-ngx.env"
    owner: "{{ podman_user }}"
    group: "{{ podman_group }}"
    mode: "0600"
- name: Create paperless-ngx pod
  containers.podman.podman_pod:
    name: paperless-ngx
    state: quadlet
    quadlet_filename: paperless-ngx
    quadlet_dir: "{{ quadlet_dir }}"
    infra_name: "paperless-ngx-pod"
    ports:
      - "8001:8000"
- name: Create paperless-ngx-redis Quadlet
  containers.podman.podman_container:
    name: paperless-ngx-redis
    image: docker.io/redis:8.2.2@sha256:4521b581dbddea6e7d81f8fe95ede93f5648aaa66a9dacd581611bf6fe7527bd
    state: quadlet
    quadlet_filename: paperless-ngx-redis
    quadlet_dir: "{{ quadlet_dir }}"
    pod: paperless-ngx.pod
    volumes:
      - "{{ podman_appdata_dir }}/paperless-ngx/redis:/data:Z"
    env_file:
      - paperless-ngx-redis.env
    health_cmd: "redis-cli ping | grep PONG"
    health_startup_interval: 30s
    health_startup_retries: 5
    healthcheck_start_period: 20s
    healthcheck_timeout: 10s
    quadlet_options:
      - "NoNewPrivileges=true"
      - |
        [Service]
        Restart=always
        TimeoutStartSec=90
      - |
        [Install]
        WantedBy=default.target
- name: Create paperless-ngx-postgres Quadlet
  containers.podman.podman_container:
    name: paperless-ngx-postgres
    image: docker.io/postgres:18.0@sha256:1ffc019dae94eca6b09a49ca67d37398951346de3c3d0cfe23d8d4ca33da83fb
    state: quadlet
    quadlet_filename: paperless-ngx-postgres
    quadlet_dir: "{{ quadlet_dir }}"
    pod: paperless-ngx.pod
    volumes:
      - "{{ podman_appdata_dir }}/paperless-ngx/postgres:/var/lib/postgresql:Z"
    env_file:
      - paperless-ngx-postgres.env
    secrets:
      - paperless_db_paperless_passwd
    health_cmd: "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"
    health_startup_interval: 30s
    health_startup_retries: 5
    healthcheck_start_period: 20s
    healthcheck_timeout: 10s
    quadlet_options:
      - "NoNewPrivileges=true"
      - |
        [Service]
        Restart=always
        TimeoutStartSec=90
      - |
        [Install]
        WantedBy=default.target
- name: Create paperless-ngx Quadlet
  containers.podman.podman_container:
    name: paperless-ngx
    image: ghcr.io/paperless-ngx/paperless-ngx:2.19.2@sha256:e1e0026cdacda4bb157c024a8a1a343bd16b34d8900e7f3958598b9afebd0d38
    state: quadlet
    quadlet_filename: paperless-ngx
    quadlet_dir: "{{ quadlet_dir }}"
    pod: paperless-ngx.pod
    volumes:
      - "{{ podman_appdata_dir }}/paperless-ngx/data:/usr/src/paperless/data:Z"
      - "{{ podman_appdata_dir }}/paperless-ngx/media:/usr/src/paperless/media:Z"
      - "{{ podman_appdata_dir }}/paperless-ngx/export:/usr/src/paperless/export:Z"
      - "{{ podman_appdata_dir }}/paperless-ngx/consume:/usr/src/paperless/consume:Z"
    env_file:
      - paperless-ngx.env
    secrets:
      - paperless_secret_key
      - paperless_db_paperless_passwd
    health_cmd: "curl -fs -S --max-time 2 http://localhost:8000"
    health_startup_interval: 30s
    health_startup_retries: 5
    healthcheck_start_period: 20s
    healthcheck_timeout: 10s
    quadlet_options:
      - "NoNewPrivileges=true"
      - |
        [Service]
        Restart=always
        TimeoutStartSec=90
      - |
        [Install]
        WantedBy=default.target
- name: Open firewalld port for Paperless-ngx
  ansible.posix.firewalld:
    port: "8001/tcp"
    permanent: true
    immediate: true
    state: enabled
  notify:
    - Reload firewalld
- name: Restart Paperless-ngx pod service
  ansible.builtin.systemd_service:
    name: paperless-ngx-pod.service
    state: "restarted"
    scope: "user"
    daemon_reload: true
    enabled: true
  become_user: "{{ podman_user }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ __user_info.uid }}"
