- name: Restart sshd
  ansible.builtin.systemd_service:
    name: sshd
    state: "restarted"
    enabled: true

- name: Restart timer for automatic updates
  ansible.builtin.systemd_service:
    name: dnf5-automatic.timer
    state: "restarted"
    enabled: true

- name: Reboot system
  ansible.builtin.reboot:
