- name: restart_sshd
  ansible.builtin.systemd:
    name: sshd
    state: "restarted"
    enabled: true

- name: Restart timer for automatic updates
  ansible.builtin.systemd:
    name: dnf5-automatic.timer
    state: "restarted"
    enabled: true
