- name: start_firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: "started"
    enabled: true

- name: restart_sshd
  ansible.builtin.systemd:
    name: sshd
    state: "restarted"
    enabled: true
