---
- name: Make sure Forgejo runner instace address is set
  ansible.builtin.fail:
    msg: "Please set forgejo_runner__instance_address"
  when: forgejo_runner__instance_address == ''

- name: Make sure Forgejo runner token is set
  ansible.builtin.fail:
    msg: "Please set deploy_forgejo_runner_runner_codeberg_token"
  when: deploy_forgejo_runner_runner_codeberg_token == ''

- name: Check if website is reachable
  ansible.builtin.uri:
    url: "{{ forgejo_runner__instance_address }}"
    method: GET

- name: Check if website is reachable
  ansible.builtin.uri:
    url: "{{ forgejo_runner__instance_address }}"
    method: GET

- name: Create runner-config.yml from template
  become: true
  ansible.builtin.template:
    src: runner-config.yml.j2
    dest: "{{ forgejo_runner__user_home }}/runner-config.yml"
    owner: "{{ forgejo_runner__user }}"
    group: "{{ forgejo_runner__group }}"
    mode: "0640"
