---
- name: Load Infisical secrets
  ansible.builtin.include_tasks: ../roles/common/tasks/infisical.yaml
- name: Extract CODEBERG_RUNNER_REGISTRATION_TOKEN
  ansible.builtin.set_fact:
    deploy_forgejo_runner_runner_codeberg_token: >-
      {{
        (
          infisical_secrets_raw
          | selectattr('key', 'equalto', 'CODEBERG_RUNNER_REGISTRATION_TOKEN')
          | first
        ).value
      }}
  no_log: true
- name: Extract CODEBERG_RUNNER_REGISTRATION_UUID
  ansible.builtin.set_fact:
    deploy_forgejo_runner_runner_codeberg_uuid: >-
      {{
        (
          infisical_secrets_raw
          | selectattr('key', 'equalto', 'CODEBERG_RUNNER_REGISTRATION_UUID')
          | first
        ).value
      }}
  no_log: true
- name: Create Forgejo runner user
  ansible.builtin.import_tasks:
    file: create_forgejo_user.yaml

- name: Set runner version
  ansible.builtin.import_tasks:
    file: set_runner_version.yaml

- name: Install runner
  ansible.builtin.import_tasks:
    file: install_runner.yaml

- name: Configure runner
  ansible.builtin.import_tasks:
    file: configure_runner.yaml

- name: Configure systemd service
  ansible.builtin.import_tasks:
    file: systemd.yaml
