---
- name: Load Infisical secrets
  ansible.builtin.include_tasks: ../roles/common/tasks/infisical.yaml
- name: Extract LIBRECHAT_OPENROUTER_KEY
  ansible.builtin.set_fact:
    services_librechat_openrouter_key: >-
      {{
        (
          infisical_secrets_raw
          | selectattr('key', 'equalto', 'LIBRECHAT_OPENROUTER_KEY')
          | first
        ).value
      }}
  no_log: true
- name: Extract LIBRECHAT_CREDS_KEY
  ansible.builtin.set_fact:
    services_librechat_creds_key: >-
      {{
        (
          infisical_secrets_raw
          | selectattr('key', 'equalto', 'LIBRECHAT_CREDS_KEY')
          | first
        ).value
      }}
  no_log: true
- name: Extract LIBRECHAT_CREDS_IV
  ansible.builtin.set_fact:
    services_librechat_creds_iv: >-
      {{
        (
          infisical_secrets_raw
          | selectattr('key', 'equalto', 'LIBRECHAT_CREDS_IV')
          | first
        ).value
      }}
  no_log: true
- name: Extract LIBRECHAT_JWT_SECRET
  ansible.builtin.set_fact:
    services_librechat_jwt_secret: >-
      {{
        (
          infisical_secrets_raw
          | selectattr('key', 'equalto', 'LIBRECHAT_JWT_SECRET')
          | first
        ).value
      }}
  no_log: true
- name: Extract LIBRECHAT_JWT_REFRESH_SECRET
  ansible.builtin.set_fact:
    services_librechat_jwt_refresh_secret: >-
      {{
        (
          infisical_secrets_raw
          | selectattr('key', 'equalto', 'LIBRECHAT_JWT_REFRESH_SECRET')
          | first
        ).value
      }}
  no_log: true
- name: Extract LIBRECHAT_MEILI_MASTER_KEY
  ansible.builtin.set_fact:
    services_librechat_meili_master_key: >-
      {{
        (
          infisical_secrets_raw
          | selectattr('key', 'equalto', 'LIBRECHAT_MEILI_MASTER_KEY')
          | first
        ).value
      }}
  no_log: true
  # NOTE: Repeated in other tasks? Improve.
- name: Create folders for Librechat config and data files
  ansible.builtin.file:
    path: "{{ podman_appdata_dir }}/{{ item }}"
    state: directory
    owner: "{{ podman_user }}"
    group: "{{ podman_group }}"
    mode: "0755"
  loop:
    - librechat/config
    - librechat/logs
    - librechat/mongodb/data
    - librechat/meilisearch/data
- name: Change logs folder permissions to 777
  # See https://github.com/danny-avila/LibreChat/discussions/2141#discussioncomment-8845459
  ansible.builtin.file:
    path: "{{ podman_appdata_dir }}/librechat/logs"
    mode: "1777"
- name: Create Librechat pod
  containers.podman.podman_pod:
    name: librechat
    state: quadlet
    quadlet_filename: librechat
    quadlet_file_mode: "0644"
    quadlet_dir: "{{ quadlet_dir }}"
    infra_name: "librechat-pod"
    ports:
      - "3080:3080"
- name: Generate librechat.env from template
  ansible.builtin.template:
    src: "{{ librechat_env_template_file }}"
    dest: "{{ quadlet_dir }}/librechat.env"
    owner: "{{ podman_user }}"
    group: "{{ podman_group }}"
    mode: "0600"
- name: Generate librechat.yaml from template
  ansible.builtin.template:
    src: "{{ librechat_yaml_template_file }}"
    dest: "{{ podman_appdata_dir }}/librechat/config/librechat.yaml"
    owner: "{{ podman_user }}"
    group: "{{ podman_group }}"
    mode: "0644"
- name: Create LibreChat Quadlet
  containers.podman.podman_container:
    name: librechat
    image: ghcr.io/danny-avila/librechat:v0.8.7@sha256:c5db3331b845e1f289f8d04c0c77936c4bbe372f76730a804abc1c37e44d23a9
    state: quadlet
    quadlet_filename: librechat
    quadlet_file_mode: "0644"
    quadlet_dir: "{{ quadlet_dir }}"
    pod: librechat.pod
    volumes:
      - "{{ podman_appdata_dir }}/librechat/config/librechat.yaml:/app/librechat.yaml:Z,ro"
      - "{{ podman_appdata_dir }}/librechat/logs:/app/api/logs:Z"
    env_file:
      - librechat.env
    quadlet_options:
      - "NoNewPrivileges=true"
      - |
        [Service]
        Restart=always
      - |
        [Install]
        WantedBy=default.target
- name: Create LibreChat-mongodb Quadlet
  containers.podman.podman_container:
    name: librechat-mongodb
    image: docker.io/library/mongo:8.0.16@sha256:f4d54619262ae3bc6a0a8efbebcef970b87b8ad70697479a75ce308a6f400158
    state: quadlet
    quadlet_filename: librechat-mongodb
    quadlet_file_mode: "0644"
    quadlet_dir: "{{ quadlet_dir }}"
    pod: librechat.pod
    volumes:
      - "{{ podman_appdata_dir }}/librechat/mongodb/data:/data/db:Z"
    env_file:
      - librechat.env
    quadlet_options:
      - "NoNewPrivileges=true"
      - |
        [Service]
        Restart=always
      - |
        [Install]
        WantedBy=default.target
- name: Create LibreChat-meilisearch Quadlet
  containers.podman.podman_container:
    name: librechat-meilisearch
    image: docker.io/getmeili/meilisearch:v1.49.0@sha256:bdc7d7e7939911c40d88d6bcd01f9c72c81f7293135916d48bce241569f721bd
    state: quadlet
    quadlet_filename: librechat-meilisearch
    quadlet_file_mode: "0644"
    quadlet_dir: "{{ quadlet_dir }}"
    pod: librechat.pod
    volumes:
      - "{{ podman_appdata_dir }}/librechat/meilisearch/data:/meili_data:Z"
    env_file:
      - librechat.env
    quadlet_options:
      - "NoNewPrivileges=true"
      - |
        [Service]
        Restart=always
      - |
        [Install]
        WantedBy=default.target

- name: Create MCP-NixOS Quadlet
  containers.podman.podman_container:
    name: librechat-mcp-nixos
    image: ghcr.io/utensils/mcp-nixos:2.4.3@sha256:5a48510c4e99549fe563e7ec0af83ccd94db15da1b50f6ce8f51b6a70cf4087c
    state: quadlet
    quadlet_filename: librechat-mcp-nixos
    quadlet_file_mode: "0644"
    quadlet_dir: "{{ quadlet_dir }}"
    pod: librechat.pod
    env_file:
      - librechat.env
    quadlet_options:
      - "NoNewPrivileges=true"
      - |
        [Service]
        Restart=always
      - |
        [Install]
        WantedBy=default.target
- name: Open firewalld port for Librechat
  ansible.posix.firewalld:
    port: "3080/tcp"
    permanent: true
    immediate: true
    state: enabled
  notify:
    - Reload firewalld
