---
- name: Create folders for Proxmox Pulse
  ansible.builtin.file:
    path: "{{ podman_appdata_dir }}/pulse/data"
    state: directory
    owner: "{{ podman_user }}"
    group: "{{ podman_group }}"
    mode: "0750"
- name: Create Pulse quadlet
  containers.podman.podman_container:
    name: pulse
    image: docker.io/rcourtman/pulse:6.1.2@sha256:d1c8d64d0f5ba88799e6808a0180eda2b19e42797a4b0df07c9f8ca380eb646f
    state: quadlet
    quadlet_filename: pulse
    quadlet_file_mode: "0644"
    quadlet_dir: "{{ quadlet_dir }}"
    ports:
      - "7655:7655"
    volumes:
      - "{{ podman_appdata_dir }}/pulse/data:/data:Z"
    quadlet_options:
      - "NoNewPrivileges=true"
      - |
        [Service]
        Restart=always
      - |
        [Install]
        WantedBy=default.target
- name: Open firewalld port for Pulse
  ansible.posix.firewalld:
    port: "7655/tcp"
    permanent: true
    immediate: true
    state: enabled
  notify:
    - Reload firewalld
