- name: Install Podman and dependencies
  tags: always
  ansible.builtin.dnf:
    update_cache: true
    name:
      - acl
      - podman
      - passt
    state: present

- name: Podman user management
  block:
    - name: Create Podman group
      ansible.builtin.group:
        name: "{{ podman_group }}"
        state: present

    - name: Create Podman user
      ansible.builtin.user:
        name: "{{ podman_user }}"
        group: "{{ podman_group }}"
        create_home: true
        state: present
      register: __user_info

    - name: Check if Podman user is lingering
      ansible.builtin.stat:
        path: "/var/lib/systemd/linger/{{ podman_user }}"
      register: __user_lingering

    - name: Enable lingering for Podman user
      ansible.builtin.command: "loginctl enable-linger {{ podman_user }}"
      when: not __user_lingering.stat.exists

- name: Enable Podman auto-update service
  ansible.builtin.systemd_service:
    name: podman-auto-update
    enabled: true
    state: "started"
    scope: "user"
    daemon_reload: true
  become: true
  become_user: "{{ podman_user }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ __user_info.uid }}"

- name: Enable Podman auto-update timer
  ansible.builtin.systemd_service:
    name: podman-auto-update.timer
    enabled: true
    state: "started"
    scope: "user"
    daemon_reload: true
  become: true
  become_user: "{{ podman_user }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ __user_info.uid }}"

- name: Create folder for Podman containers
  ansible.builtin.file:
    path: "{{ quadlet_dir }}"
    state: directory
    owner: "{{ podman_user }}"
    group: "{{ podman_group }}"
    mode: "0755"
