---
- name: Update APT packages on Debian/Ubuntu
  ansible.builtin.apt:
    name: "*"
    update_cache: true
    state: latest
    autoremove: true
  when: ansible_os_family == "Debian" or ansible_os_family == "Zorin OS"

- name: Update Flatpaks
  ansible.builtin.command: flatpak update --noninteractive
  register: flatpak_update_output
  changed_when: "'app/' in flatpak_update_output.stdout"
  when: ansible_os_family == "Zorin OS"

- name: Reboot if required
  when:
    - ansible_os_family == "Debian" or ansible_os_family == "Zorin OS"
  block:
    - name: Check if reboot required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot if required
      ansible.builtin.reboot:
      when:
        - reboot_required_file.stat.exists

- name: Update DNF packages on Fedora
  ansible.builtin.dnf5:
    name: "*"
    state: latest
  when: ansible_os_family == "RedHat"

- name: Remove packages that are not longer needed
  ansible.builtin.dnf5:
    autoremove: true
  when: ansible_os_family == "RedHat"
