- name: Install Fedora packages
  tags: fedora
  ansible.builtin.dnf:
    update_cache: true
    name: "{{ item }}"
    state: present
  loop:
    - dnf-automatic
    - firewalld
  when: ansible_distribution == "Fedora"

- name: Enable and start FirewallD
  ansible.builtin.systemd:
    name: firewalld
    state: "started"
    daemon_reload: true
    enabled: true
  when: ansible_distribution == "Fedora"

- block:
    - name: Enable a timer unit for dnf5-automatic
      ansible.builtin.systemd_service:
        name: dnf5-automatic.timer
        state: started
        enabled: true
      when: ansible_distribution == "Fedora"

    - name: Creating configuration file for dnf5-automatic
      ansible.builtin.copy:
        dest: /etc/dnf/automatic.conf
        owner: root
        group: root
        mode: "0644"
        content: |
          [commands]
          apply_updates = yes
          reboot = when-needed
      notify: Restart timer for automatic updates
      when: ansible_distribution == "Fedora"

- block:
    - name: Generate sshd_config from template
      tags: fedora,ssh
      ansible.builtin.template:
        src: "{{ sshd_template_file }}"
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: "0644"
      notify: restart_sshd
      when: ansible_distribution == "Fedora"

    - name: Set SSH crypto-policies
      tags: fedora,ssh
      ansible.builtin.copy:
        src: opensshserver.config
        dest: /etc/crypto-policies/back-ends/opensshserver.config
        follow: true
        owner: root
        group: root
        mode: "0644"
      notify:
        - restart_sshd
      when: ansible_distribution == "Fedora"
