- name: Install Fedora packages
  tags: fedora
  ansible.builtin.dnf:
    update_cache: true
    name: "{{ item }}"
    state: latest
  loop:
    - dnf-automatic
    - firewalld
  when: ansible_distribution == "Fedora"

- name: Enable and start FirewallD
  ansible.builtin.systemd:
    name: firewalld
    state: "started"
    daemon_reload: true
    enabled: true
  when: ansible_distribution == "Fedora"

- block:
  - name: Enable a timer unit for dnf-automatic
    ansible.builtin.systemd_service:
      name: dnf-automatic.timer
      state: started
      enabled: true
    when: ansible_distribution == "Fedora"
  - name: Apply updates automatically
    ansible.builtin.lineinfile:
      path: /etc/dnf/automatic.conf
      regexp: ^apply_updates = no
      line: apply_updates = yes
    notify: Restart timer for automatic updates
    when: ansible_distribution == "Fedora"
  - name: Reboot after updates if needed
    ansible.builtin.lineinfile:
      path: /etc/dnf/automatic.conf
      regexp: ^reboot = no
      line: reboot = when-needed
    notify: Restart timer for automatic updates
    when: ansible_distribution == "Fedora"
- block:
  - name: Generate sshd_config from template
    tags: fedora,ssh
    template:
      src: "{{ sshd_template_file }}"
      dest: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: "0644"
    notify: restart_sshd
    when: ansible_distribution == "Fedora"

  - name: Set SSH crypto-policies
    tags: fedora,ssh
    ansible.builtin.copy:
      src: opensshserver.config
      dest: /etc/crypto-policies/back-ends/opensshserver.config
      follow: true
      owner: root
      group: root
      mode: "0644"
    notify:
      - restart_sshd
    when: ansible_distribution == "Fedora"

- name: Update Debian/Ubuntu apt update_cache
  ansible.builtin.apt:
    update_cache: true

- name: Install Debian/Ubuntu packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: "latest"
  loop:
    - ufw
    - unattended-upgrades
