---
- name: Install Podman and dependencies
  tags: always
  ansible.builtin.dnf:
    update_cache: true
    name:
      - acl
      - podman
      - passt
    state: present
- name: Podman user management
  block:
    - name: Create Podman group
      ansible.builtin.group:
        name: "{{ podman_group }}"
        state: present
    - name: Create Podman user
      ansible.builtin.user:
        name: "{{ podman_user }}"
        group: "{{ podman_group }}"
        create_home: true
        state: present
      register: __user_info
    - name: Check if Podman user is lingering
      ansible.builtin.stat:
        path: "/var/lib/systemd/linger/{{ podman_user }}"
      register: __user_lingering
    - name: Enable lingering for Podman user
      ansible.builtin.command: "loginctl enable-linger {{ podman_user }}"
      when: not __user_lingering.stat.exists
- name: Disable Podman auto-update service
  ansible.builtin.systemd_service:
    name: podman-auto-update
    enabled: false
    state: "stopped"
    scope: "user"
    daemon_reload: true
  become: true
  become_user: "{{ podman_user }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ __user_info.uid }}"
- name: Enable Podman auto-update timer
  ansible.builtin.systemd_service:
    name: podman-auto-update.timer
    enabled: false
    state: "stopped"
    scope: "user"
    daemon_reload: true
  become: true
  become_user: "{{ podman_user }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ __user_info.uid }}"
- name: Create folder for Podman containers
  ansible.builtin.file:
    path: "{{ quadlet_dir }}"
    state: directory
    owner: "{{ podman_user }}"
    group: "{{ podman_group }}"
    mode: "0755"

- name: Create filesystem for persistent data
  # NOTE: it will skip the task if the filesystem already exists
  # Be very careful to not having to restore from backup
  community.general.filesystem:
    fstype: "ext4"
    dev: "/dev/sdb" # scsi2 in Proxmox

- name: Read filesystem UUID
  ansible.builtin.command:
    argv:
      - blkid
      - -s
      - UUID
      - -o
      - value
      - /dev/sdb
  register: __podman_disk_uuid
  changed_when: false

- name: Create mount point
  ansible.builtin.file:
    path: "/srv/podman"
    state: directory
    mode: "0750"
    owner: "{{ podman_user }}"
    group: "{{ podman_group }}"

- name: Mount disk and persist in fstab
  ansible.posix.mount:
    path: "/srv/podman"
    src: "UUID={{ __podman_disk_uuid.stdout | trim }}"
    fstype: "ext4"
    opts: defaults,nofail
    state: mounted
