- name: Reload daemon
  ansible.builtin.systemd_service:
    daemon_reload: true
- name: Reload Crowdsec
  ansible.builtin.systemd_service:
    name: crowdsec
    state: reloaded
- name: Reload Caddy
  ansible.builtin.shell: |
    caddy reload -c /etc/caddy/Caddyfile
